//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryAppMVVM.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratoryDatabaseEntities : DbContext
    {
        public LaboratoryDatabaseEntities()
            : base("name=LaboratoryDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analyzer> Analyzers { get; set; }
        public virtual DbSet<AppliedService> AppliedServices { get; set; }
        public virtual DbSet<BarcodeOfPatient> BarcodeOfPatients { get; set; }
        public virtual DbSet<HistoryOfLogin> HistoryOfLogins { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompanies { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<StatusOfAppliedService> StatusOfAppliedServices { get; set; }
        public virtual DbSet<TypeOfInsurancePolicy> TypeOfInsurancePolicies { get; set; }
        public virtual DbSet<TypeOfUser> TypeOfUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
